name = "mobile-app-builder"
main = "src/index.js"
compatibility_date = "2026-09-06"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1
redact_query_string = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
persist = true
destinations = ["cloudflare"]

[observability.traces]
enabled = true
head_sampling_rate = 0.01
persist = true
destinations = ["cloudflare"]
